### PR TITLE
saved presentation to doc and updated charts

### PR DESCRIPTION
**Pull request by earroyo28**
saved the presentation in pdf format and the updated charts to the doc directory

### CODE REVIEW

**Comment by rjpecoraro** [comment]
Can you change the name of the purple one to chart.png? That way it will replace the existing diagram.

**Comment by rjpecoraro** [comment]
Also is the structure figure going anywhere else (like in a README)? Otherwise I think it might be fine to skip since it's already in the presentation

**Comment by jiaweih** [comment]
Thank you

**Comment by earroyo28** [comment]
I renamed the design chart to chart.png

**Comment by rjpecoraro** [comment]
Awesome, looks good to me!

**Pull request merged**
